### ISSUE TITLE
Distill finished! 0 -> 0 (0 discarded)

### ISSUE THREAD

**Issue by vishaljoshi24** [zhudotexe/aws-kinesis-dataset-exploration-tool#7]
I've made sure all the dependencies are properly installed and have downloaded and extracted the dataset. The DATA_DIR path is "fireball-anonymized-nov-28-2022-kfdjl/anonymized/data/". Whenever I run distill1_time_group.py I get the above output in my terminal. Running then through the rest of the files until finetune_prep.py gives a error which states there is no training data.

**Comment by zhudotexe** [comment]
Hi Vishal, this repository contains all the scripts we used to produce the data files in the FIREBALL release for reference - you probably won't need to use any of the code here unless you're reproducing the dataset. If you would like to do that for whatever reason, your `DATA_DIR` should be a directory containing multiple other directories, where each subdirectory is named the ID of a combat instance and contains one or more JSONL files (the `raw.jsonl` files in the FIREBALL release).

I recommend just using the preprocessed outputs included in FIREBALL though.

**Comment by vishaljoshi24** [comment]
Hi Andrew,

Thank you for the clarification, I will look at the FIREBALL repository instead. Thank you.

Kind regards,
Vishal Joshi

***@***.***?anonymous&ep=owaSlotsEmailSignature>               Book time to meet with ***@***.***?anonymous&ep=owaSlotsEmailSignature>

________________________________
